# Generated by Django 5.1.1 on 2024-10-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0016_category_seo_description_category_seo_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_keywords',
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
    ]
